[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb-led-scoreboard-green-monster"
version = "1.5.1"
description = "Green Monster-style game display for MLB-LED-Scoreboard Bullpen"
license = "GPL-3.0-or-later"
dependencies = ["MLB_StatsAPI>=1.9.0"]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'bullpen.mlbled.plugin']
"green_monster" = "mlb_led_scoreboard_green_monster:load"
